### ISSUE TITLE
释义的宽度限制，以及单词的释义可以修改

### ISSUE THREAD

**Issue by gaoluji** [jackhatedance/my-english-reading-assistant#29]
有些情况下，一个句子中有多个生词，而释义太长会折叠。
![image](https://github.com/user-attachments/assets/e564d958-2c52-456e-879e-490daaea5527)
## 解决
1. 限制宽度，一个释义不超过单词的长度
2. 纵向显示： - 单词的释义回车显示到下一行（行高可能需要调整）
## 单词高亮
生词是否可以显示别的颜色？

**Comment by jackhatedance** [comment]
问题：
生词比较多的时候，释义重叠了。

目前的解决方案：
光标移到某个单词上，该单词的释义会突出显示。下图，光标在Array单词上。
<img width="420" alt="Screenshot 2024-07-19 at 14 07 37" src="https://github.com/user-attachments/assets/afc8bd94-5ccb-457f-b568-d7de158fd22f">

建议的解决方案：
1. 限制宽度。

评论：单词的释义长短不一，如果强行截断，可能导致看不全。

2. 纵向显示。

评论：目前的释义是以CSS  ::after的形式添加的，无法做到换行。 这种形式的好处是如果用户选择正文内容，释义不会被选中。也就是侵入性不强。如果换用其他技术方案，比如span，确实可以做到换行。将来可以考虑让用户自己选择其中一种方案。

3. 单词高亮
评论： 这个好办。

**Comment by jackhatedance** [comment]
在v0.8.4版本里可以设置单词含义的最大数量，默认长度为3个含义。

**Comment by jackhatedance** [comment]
v0.8.5 支持生词高亮
